[package]
name = "second_xml"
version = "0.1.0"
edition = "2024"

[dependencies]
quick-xml = { version = "0.38.4", features = ["serde"] }
serde = { version = "1.0.228", features = ["derive"] }
serde-xml-rs = "0.8.2"
